name: 'Google Charts'
type: module
description: 'Charts module integration with Google Charts.'
package: Charts
# core: 8.x
dependencies:
  - 'charts:charts'

# Information added by Drupal.org packaging script on 2018-06-29
version: '8.x-3.0-alpha10+12-dev'
core: '8.x'
project: 'charts'
datestamp: 1530287327
